# -*- coding: utf-8 -*-
# (anahtar, tr, en, ar, fr)  — {0},{1}... yer tutucuları
T = []
def a(k, tr, en, ar, fr): T.append((k, tr, en, ar, fr))

# genel
a("ok","Tamam","OK","حسناً","OK")
a("cancel","Vazgeç","Cancel","إلغاء","Annuler")
a("none","Yok","None","لا يوجد","Aucun")
a("on","Açık","On","مفعّل","Activé")
a("off","Kapalı","Off","معطّل","Désactivé")
a("max","Maks","Max","الأقصى","Max")
a("loading","Yükleniyor…","Loading…","جارٍ التحميل…","Chargement…")
a("loading_done","Hazır!","Ready!","جاهز!","Prêt !")
a("lvl_short","Sv. {0}","Lv. {0}","مستوى {0}","Niv. {0}")
a("level","Seviye","Level","المستوى","Niveau")
a("max_level","Maksimum seviyedesin.","You reached the max level.","وصلت إلى أعلى مستوى.","Niveau maximum atteint.")
a("xp_line","{0} / {1} XP • sonraki seviyeye {2} XP","{0} / {1} XP • {2} XP to next level","{0} / {1} نقطة خبرة • {2} للمستوى التالي","{0} / {1} XP • {2} XP avant le niveau suivant")
a("balance","Bakiye","Balance","الرصيد","Solde")
a("year_km","Yıl • Kilometre","Year • Mileage","السنة • المسافة","Année • Kilométrage")
a("est_value","Tahmini değer","Estimated value","القيمة التقديرية","Valeur estimée")
a("asking","İstenen fiyat","Asking price","السعر المطلوب","Prix demandé")
a("seller","Satıcı","Seller","البائع","Vendeur")
a("credits","Yapımcılar","Created by","صنع بواسطة","Créé par")

# menü / ana ekran
a("btn_new_game","OYUNA BAŞLA","START GAME","ابدأ اللعبة","NOUVELLE PARTIE")
a("btn_continue","KALDIĞIN YERDEN DEVAM ET","CONTINUE","تابع من حيث توقفت","CONTINUER")
a("btn_settings","AYARLAR","SETTINGS","الإعدادات","PARAMÈTRES")
a("no_save","Kayıtlı oyun bulunamadı.","No saved game found.","لا توجد لعبة محفوظة.","Aucune sauvegarde trouvée.")
a("new_game_title","Yeni Galeri","New Gallery","معرض جديد","Nouvelle galerie")
a("new_game_name","Galeri sahibinin adı","Owner name","اسم صاحب المعرض","Nom du propriétaire")
a("new_game_city","Konum","Location","الموقع","Lieu")
a("new_game_hint","Başlangıç bakiyesi: {0}. Sıfırdan başlıyorsun!","Starting balance: {0}. You start from zero!","الرصيد الابتدائي: {0}. تبدأ من الصفر!","Solde de départ : {0}. Tu pars de zéro !")
a("new_game_overwrite","Mevcut kayıt silinecek.","The existing save will be overwritten.","سيتم استبدال الحفظ الحالي.","La sauvegarde existante sera écrasée.")
a("default_name","Patron","Boss","المدير","Patron")
a("btn_start","BAŞLA","START","ابدأ","DÉMARRER")
a("welcome_title","Hoş geldin!","Welcome!","مرحباً!","Bienvenue !")
a("welcome_body","Araç Pazarı'ndan ilk aracını bul, ekspertiz yap, pazarlık et, hazırla ve sat. Sıradaki hedef her zaman ana ekranda görünür.","Find your first car in the Car Market, inspect it, haggle, prepare it and sell it. Your next goal is always on the home screen.","ابحث عن أول سيارة في سوق السيارات، افحصها، فاوض، جهّزها ثم بعها. هدفك التالي يظهر دائماً في الشاشة الرئيسية.","Trouve ta première voiture au Marché Auto, expertise-la, négocie, prépare-la et vends-la. Ton prochain objectif est toujours sur l'accueil.")
a("home_hello","Merhaba, {0}","Hello, {0}","مرحباً، {0}","Bonjour, {0}")
a("home_sub","{0}","{0}","{0}","{0}")
a("lvl_title_0","Çaylak Galerici","Rookie Dealer","تاجر مبتدئ","Concessionnaire débutant")
a("lvl_title_1","Deneyimli Galerici","Seasoned Dealer","تاجر خبير","Concessionnaire confirmé")
a("lvl_title_2","Usta Tüccar","Master Trader","تاجر محترف","Maître négociant")
a("lvl_title_3","Bölge Patronu","District Boss","زعيم المنطقة","Patron du quartier")
a("lvl_title_4","Şehrin Galericisi","City Magnate","قطب المدينة","Magnat de la ville")
a("lvl_title_5","OtoPatron","OtoPatron","أوتو باترون","OtoPatron")
a("goal_title","SIRADAKİ HEDEF","NEXT GOAL","الهدف التالي","PROCHAIN OBJECTIF")
a("goal_go","Git","Go","اذهب","Y aller")
a("goal_buy","Araç Pazarı'na git ve ilk aracını bul.","Visit the Car Market and find your first car.","اذهب إلى سوق السيارات وابحث عن أول سيارة.","Va au Marché Auto et trouve ta première voiture.")
a("goal_list","Aracını hazırla ve ilan ver.","Prepare your car and list it for sale.","جهّز سيارتك وأعلن عنها للبيع.","Prépare ta voiture et mets-la en vente.")
a("goal_wait","İlanlar yayında: müşteri için zamanı ilerlet.","Cars are listed: advance time to attract customers.","السيارات معروضة: مرّر الوقت لجذب الزبائن.","Annonces en ligne : fais avancer le temps pour attirer des clients.")
a("goal_visit","Bir müşteri seni bekliyor. Görüşmeye geç!","A customer is waiting. Talk to them!","زبون ينتظرك. تحدث معه!","Un client t'attend. Va lui parler !")
a("goal_reward","Seviye ödülünü seç!","Pick your level reward!","اختر مكافأة المستوى!","Choisis ta récompense de niveau !")
a("reward_waiting","Ödül seni bekliyor ({0})","Reward waiting ({0})","مكافأة بانتظارك ({0})","Récompense en attente ({0})")
a("debt_total","Toplam kredi borcu","Total loan debt","إجمالي الدين","Dette totale")
a("next_installment","Sıradaki taksit","Next installment","القسط التالي","Prochaine échéance")
a("no_debt","Kredi borcun yok.","You have no debt.","لا توجد ديون.","Aucune dette.")
a("menu_business","İşletmem","My Business","عملي","Mon commerce")
a("menu_market","Araç Pazarı","Car Market","سوق السيارات","Marché Auto")
a("menu_training","Eğitim","Training","التدريب","Formation")
a("menu_loans","Kredi","Loans","القروض","Crédits")
a("menu_settings","Ayarlar","Settings","الإعدادات","Paramètres")
a("menu_profile","Profil","Profile","الملف","Profil")
a("btn_save","Kaydet","Save","حفظ","Sauvegarder")
a("btn_load","Yükle","Load","تحميل","Charger")
a("saved","Oyun kaydedildi.","Game saved.","تم حفظ اللعبة.","Partie sauvegardée.")
a("loaded","Kayıt yüklendi.","Save loaded.","تم تحميل الحفظ.","Sauvegarde chargée.")
a("nav_home","Ana Sayfa","Home","الرئيسية","Accueil")
a("nav_garage","İşletmem","Business","عملي","Commerce")
a("nav_market","Pazar","Market","السوق","Marché")
a("nav_training","Eğitim","Training","التدريب","Formation")
a("nav_loans","Kredi","Loans","القروض","Crédits")
a("fx_demand","Talep","Demand","الطلب","Demande")
a("fx_none","Piyasaya etkisi yok","No market effect","لا تأثير على السوق","Aucun effet sur le marché")
a("city_ist","İstanbul","Istanbul","إسطنبول","Istanbul")
a("city_ank","Ankara","Ankara","أنقرة","Ankara")
for i,(tr,en,ar,fr) in enumerate([("Ocak","January","يناير","janvier"),("Şubat","February","فبراير","février"),("Mart","March","مارس","mars"),("Nisan","April","أبريل","avril"),("Mayıs","May","مايو","mai"),("Haziran","June","يونيو","juin"),("Temmuz","July","يوليو","juillet"),("Ağustos","August","أغسطس","août"),("Eylül","September","سبتمبر","septembre"),("Ekim","October","أكتوبر","octobre"),("Kasım","November","نوفمبر","novembre"),("Aralık","December","ديسمبر","décembre")],1):
    a("month_%d"%i,tr,en,ar,fr)
for i,(tr,en,ar,fr) in enumerate([("Pazar","Sun","الأحد","dim"),("Pzt","Mon","الاثنين","lun"),("Sal","Tue","الثلاثاء","mar"),("Çar","Wed","الأربعاء","mer"),("Per","Thu","الخميس","jeu"),("Cum","Fri","الجمعة","ven"),("Cmt","Sat","السبت","sam")]):
    a("wd_%d"%i,tr,en,ar,fr)
a("wx_sunny","Güneşli","Sunny","مشمس","Ensoleillé")
a("wx_cloudy","Bulutlu","Cloudy","غائم","Nuageux")
a("wx_rain","Yağmurlu","Rainy","ماطر","Pluvieux")
a("wx_snow","Karlı","Snowy","مثلج","Neigeux")
a("news_calm","Piyasa sakin.","The market is calm.","السوق هادئ.","Marché calme.")
a("news_fuel","Akaryakıta zam geldi.","Fuel prices went up.","ارتفعت أسعار الوقود.","Hausse des prix du carburant.")
a("news_ev","Elektrikli araç teşviki duyuruldu.","EV incentives announced.","الإعلان عن حوافز للسيارات الكهربائية.","Aides pour véhicules électriques annoncées.")
a("news_holiday","Tatil sezonu: alışveriş hareketli.","Holiday season: shoppers are out.","موسم العطلات: حركة شراء نشطة.","Période de vacances : les acheteurs sont là.")
a("news_rates_down","Kredi faizleri düştü.","Loan rates dropped.","انخفضت أسعار الفائدة.","Les taux de crédit ont baissé.")
a("news_rates_up","Kredi faizleri yükseldi.","Loan rates rose.","ارتفعت أسعار الفائدة.","Les taux de crédit ont augmenté.")
a("news_auction","Büyük bir ikinci el araç ihalesi yapıldı.","A large used-car auction took place.","أقيم مزاد كبير للسيارات المستعملة.","Grosse vente aux enchères de voitures d'occasion.")
a("news_lux_tax","Lüks araç vergisi artırıldı.","Luxury car tax increased.","زيادة ضريبة السيارات الفاخرة.","Hausse de la taxe sur les voitures de luxe.")
a("news_truck","Ticari araç talebi arttı.","Commercial vehicle demand rose.","ارتفع الطلب على المركبات التجارية.","La demande de véhicules utilitaires augmente.")
for k,tr,en,ar,fr in [("eco","Ekonomik","Economy","اقتصادية","Économique"),("mid","Orta Sınıf","Mid-range","متوسطة","Milieu de gamme"),("suv","SUV","SUV","دفع رباعي","SUV"),("com","Ticari","Commercial","تجارية","Utilitaire"),("sport","Spor","Sport","رياضية","Sportive"),("ev","Elektrikli","Electric","كهربائية","Électrique"),("lux","Lüks","Luxury","فاخرة","Luxe")]:
    a("cls_"+k,tr,en,ar,fr)

# pazar / ilan
a("market_title","Araç Pazarı","Car Market","سوق السيارات","Marché Auto")
a("market_sub","Bugün {0} ilan var. İlanlar her gün yenilenir.","{0} listings today. They refresh daily.","{0} إعلاناً اليوم. تتجدد يومياً.","{0} annonces aujourd'hui, renouvelées chaque jour.")
a("btn_inspect_open","İncele ve Pazarlık Et","Inspect & Haggle","افحص وفاوض","Inspecter et négocier")
a("listing_title","İlan Detayı","Listing","تفاصيل الإعلان","Annonce")
a("listing_gone","Bu ilan artık yok.","This listing is gone.","هذا الإعلان لم يعد متاحاً.","Cette annonce n'existe plus.")
a("inspect_title","Ekspertiz","Inspection","الفحص","Expertise")
a("inspect_hint","Her parça için ücret: {0}. Sonuçlar risk ve kâr kararını etkiler.","Fee per part: {0}. Results affect your risk and profit.","رسوم كل جزء: {0}. النتائج تؤثر على المخاطرة والربح.","Frais par élément : {0}. Les résultats influencent risque et profit.")
a("btn_inspect","İncele ({0})","Inspect ({0})","افحص ({0})","Inspecter ({0})")
a("part_engine","Motor","Engine","المحرك","Moteur")
a("part_body","Kaporta","Body","الهيكل","Carrosserie")
a("part_tires","Lastikler","Tires","الإطارات","Pneus")
a("part_interior","İç Mekân","Interior","الداخلية","Intérieur")
a("state_good","İyi","Good","جيد","Bon")
a("state_mid","Orta","Fair","متوسط","Moyen")
a("state_bad","Kötü","Poor","سيئ","Mauvais")
a("state_unknown","İncelenmedi","Not inspected","لم يُفحص","Non inspecté")
a("repair_est","Tamir: {0} – {1}","Repair: {0} – {1}","الإصلاح: {0} – {1}","Réparation : {0} – {1}")
a("btn_call_seller","Satıcıyı Ara ve Pazarlık Et","Call Seller & Haggle","اتصل بالبائع وفاوض","Appeler et négocier")
a("btn_buy_ask","İstenen Fiyata Satın Al ({0})","Buy at Asking ({0})","اشترِ بالسعر المطلوب ({0})","Acheter au prix demandé ({0})")
a("toast_bought","{0} satın alındı!","{0} purchased!","تم شراء {0}!","{0} acheté !")
a("err_no_money","Yetersiz bakiye.","Not enough money.","الرصيد غير كافٍ.","Solde insuffisant.")
a("need_money_body","{0} eksiğin var. Kredi alabilirsin.","You are short by {0}. You can take a loan.","ينقصك {0}. يمكنك أخذ قرض.","Il te manque {0}. Tu peux prendre un crédit.")
a("btn_take_loan","Kredi Al","Take a Loan","خذ قرضاً","Prendre un crédit")
a("err_no_space","Galeride yer yok.","No space in the gallery.","لا توجد مساحة في المعرض.","Plus de place dans la galerie.")
a("no_space_body","Önce bir aracı sat veya galeri kapasitesini artır.","Sell a car first or upgrade your gallery capacity.","بع سيارة أولاً أو وسّع سعة المعرض.","Vends une voiture ou agrandis ta galerie.")
a("call_title","{0} ile görüşme","Call with {0}","مكالمة مع {0}","Appel avec {0}")
a("call_ringing","Aranıyor…","Calling…","جارٍ الاتصال…","Appel en cours…")
a("sell_greet","Alo, ilan için mi arıyorsunuz? Fiyat {0}.","Hello, calling about the ad? The price is {0}.","ألو، تتصل بخصوص الإعلان؟ السعر {0}.","Allô, c'est pour l'annonce ? Le prix est de {0}.")
a("your_offer","Teklifin","Your offer","عرضك","Ton offre")
a("offer_bubble","{0} verebilirim.","I can pay {0}.","يمكنني دفع {0}.","Je peux payer {0}.")
a("btn_send_offer","Teklifi Gönder","Send Offer","أرسل العرض","Envoyer l'offre")
a("btn_hang_up","Aramayı Bitir","Hang Up","أنهِ المكالمة","Raccrocher")
a("btn_accept_counter","Karşı Teklifi Kabul Et ({0})","Accept Counter ({0})","اقبل العرض المضاد ({0})","Accepter la contre-offre ({0})")
a("btn_buy_at","{0} ile Satın Al","Buy at {0}","اشترِ بـ {0}","Acheter à {0}")
a("sell_accept","Tamam, anlaştık. {0} olsun.","Alright, deal. {0} it is.","حسناً، اتفقنا. {0}.","D'accord, marché conclu. {0}.")
a("sell_counter","Hımm… {0} olursa düşünürüm.","Hmm… I could do {0}.","همم… قد أقبل بـ {0}.","Hmm… je peux faire {0}.")
a("sell_sad","Bu teklif biraz kırıcı… {0}'den aşağı inemem.","That's a bit insulting… I can't go below {0}.","هذا العرض مهين قليلاً… لا أستطيع النزول عن {0}.","C'est vexant… je ne descends pas sous {0}.")
a("sell_angry","Ciddi misiniz?! Bu fiyata aracımı verecek değilim!","Are you serious?! I'm not giving the car away!","هل أنت جاد؟! لن أعطي سيارتي بهذا السعر!","Sérieusement ?! Je ne brade pas ma voiture !")
a("sell_end","Yeter, görüşmeyi bitiriyorum. İyi günler.","That's enough, I'm ending this call. Goodbye.","كفى، سأنهي المكالمة. مع السلامة.","Ça suffit, je raccroche. Au revoir.")

# işletmem
a("garage_title","İşletmem","My Business","عملي","Mon commerce")
a("capacity","Galeri kapasitesi","Gallery capacity","سعة المعرض","Capacité de la galerie")
a("capacity_max","Galeri en üst kapasitede.","Gallery is at max capacity.","المعرض في أقصى سعة.","Galerie à capacité maximale.")
a("upgrade_info","Sonraki geliştirme: {0} araç kapasitesi • {1} • Seviye {2} gerekir.","Next upgrade: {0} car slots • {1} • requires level {2}.","الترقية التالية: {0} مكاناً • {1} • يتطلب المستوى {2}.","Prochaine amélioration : {0} places • {1} • niveau {2} requis.")
a("btn_upgrade","Geliştir ({0})","Upgrade ({0})","طوّر ({0})","Améliorer ({0})")
a("toast_upgraded","Galeri kapasitesi {0} araca çıktı!","Gallery capacity is now {0} cars!","أصبحت سعة المعرض {0} سيارة!","Capacité de la galerie : {0} voitures !")
a("err_level","Seviyen yetersiz.","Your level is too low.","مستواك غير كافٍ.","Niveau insuffisant.")
a("time_title","Saat: {0}","Time: {0}","الوقت: {0}","Heure : {0}")
a("wait_1h","+1 saat","+1 hour","+1 ساعة","+1 heure")
a("wait_3h","+3 saat","+3 hours","+3 ساعات","+3 heures")
a("wait_day","Günü bitir","End day","أنهِ اليوم","Fin de journée")
a("visits_title","Müşteri ziyaretleri ({0})","Customer visits ({0})","زيارات الزبائن ({0})","Visites de clients ({0})")
a("visits_empty","Şu an bekleyen müşteri yok. Araçlarını ilana koy ve zamanı ilerlet.","No customers waiting. List your cars and advance time.","لا زبائن بالانتظار. اعرض سياراتك ومرّر الوقت.","Aucun client. Mets tes voitures en vente et fais avancer le temps.")
a("cust_student","Öğrenci","Student","طالب","Étudiant")
a("cust_trader","Esnaf","Tradesman","صاحب مهنة","Artisan")
a("cust_family","Aile","Family","عائلة","Famille")
a("cust_corp","Kurumsal","Corporate","شركة","Entreprise")
a("cust_vip","VIP","VIP","كبار الشخصيات","VIP")
a("btn_talk","Görüş","Talk","تحدث","Parler")
a("my_cars","Araçlarım","My Cars","سياراتي","Mes voitures")
a("garage_empty","Galeride araç yok.","No cars in your gallery.","لا توجد سيارات في معرضك.","Aucune voiture dans ta galerie.")
a("listed_at","İlanda: {0}","Listed: {0}","معروضة: {0}","En vente : {0}")
a("not_listed","İlanda değil","Not listed","غير معروضة","Non listée")
a("btn_manage","Hazırla ve Yönet","Prepare & Manage","جهّز وأدِر","Préparer et gérer")
a("storage_title","Depo ({0}/{1})","Storage ({0}/{1})","المخزن ({0}/{1})","Dépôt ({0}/{1})")
a("btn_to_garage","Galeriye al","Move to gallery","انقل إلى المعرض","Mettre en galerie")
a("btn_to_market","Pazara aktar ({0})","Sell to market ({0})","بع للسوق ({0})","Vendre au marché ({0})")
a("visit_title","Müşteri: {0}","Customer: {0}","الزبون: {0}","Client : {0}")
a("cust_greet","Merhaba, aracınıza bakmaya geldim. {0} veririm.","Hello, I came to see your car. I'd pay {0}.","مرحباً، جئت لأرى سيارتك. سأدفع {0}.","Bonjour, je viens voir votre voiture. Je propose {0}.")
a("btn_accept_offer","Teklifi Kabul Et ({0})","Accept Offer ({0})","اقبل العرض ({0})","Accepter l'offre ({0})")
a("your_counter","Karşı teklifin","Your counter-offer","عرضك المضاد","Ta contre-offre")
a("btn_send_counter","Karşı Teklif Gönder","Send Counter-offer","أرسل عرضاً مضاداً","Envoyer la contre-offre")
a("btn_dismiss","Müşteriyi Gönder","Dismiss Customer","اصرف الزبون","Congédier le client")
a("counter_bubble","Bu araç için {0} istiyorum.","I want {0} for this car.","أريد {0} لهذه السيارة.","Je veux {0} pour cette voiture.")
a("cust_accept","Tamam, anlaştık!","Okay, we have a deal!","حسناً، اتفقنا!","D'accord, marché conclu !")
a("cust_counter","Biraz indirin… {0} olur.","Come down a bit… {0} works.","أنزل قليلاً… {0} مناسب.","Baissez un peu… {0} ça va.")
a("cust_low","Bu fiyat bütçemin çok üstünde.","That is far above my budget.","هذا السعر أعلى بكثير من ميزانيتي.","C'est bien au-dessus de mon budget.")
a("cust_leave","Anlaşamadık, başka galeriye bakacağım.","We can't agree, I'll check another gallery.","لم نتفق، سأذهب إلى معرض آخر.","On ne s'entend pas, je vais voir ailleurs.")
a("toast_visit","{0} için bir müşteri geldi!","A customer came for {0}!","جاء زبون من أجل {0}!","Un client est venu pour {0} !")
a("sale_title","Satış Tamamlandı!","Sale Complete!","تمت عملية البيع!","Vente conclue !")
a("sale_income","Satış geliri","Sale income","إيراد البيع","Revenu de la vente")
a("sale_bought","Alış bedeli","Purchase cost","سعر الشراء","Prix d'achat")
a("sale_expenses","Masraflar (tamir/temizlik)","Expenses (repair/cleaning)","المصاريف (إصلاح/تنظيف)","Frais (réparation/nettoyage)")
a("sale_net","Net kâr","Net profit","صافي الربح","Bénéfice net")
a("sale_xp","Kazanılan XP","XP earned","الخبرة المكتسبة","XP gagnée")
a("sale_installment","Sıradaki kredi taksiti","Next loan installment","القسط التالي","Prochaine échéance")
a("level_up_line","Seviye atladın! Yeni seviye: {0}","Level up! New level: {0}","ارتقيت! المستوى الجديد: {0}","Niveau supérieur ! Nouveau niveau : {0}")
a("btn_pick_reward","Ödülünü Seç","Pick Your Reward","اختر مكافأتك","Choisir la récompense")
a("btn_continue_game","Devam","Continue","متابعة","Continuer")
a("toast_levelup","Seviye {0}!","Level {0}!","المستوى {0}!","Niveau {0} !")

# araç yönetimi
a("car_title","Araç Yönetimi","Car Management","إدارة السيارة","Gestion du véhicule")
a("next_step_prep","Sıradaki adım: aracı hazırla ve ilana koy.","Next step: prepare the car and list it.","الخطوة التالية: جهّز السيارة وأعلن عنها.","Étape suivante : prépare la voiture et mets-la en vente.")
a("prep_title","Hazırlık","Preparation","التجهيز","Préparation")
a("prep_hint","Tamir değeri artırır ama masraftır. Aracı olduğu gibi de satabilirsin.","Repairs raise value but cost money. You can also sell as-is.","الإصلاح يرفع القيمة لكنه مكلف. يمكنك البيع كما هي.","Les réparations augmentent la valeur mais coûtent. Tu peux vendre en l'état.")
a("btn_repair","Tamir et ({0})","Repair ({0})","أصلح ({0})","Réparer ({0})")
a("clean","Temizlik","Cleaning","التنظيف","Nettoyage")
a("btn_clean","Temizle ({0})","Clean ({0})","نظّف ({0})","Nettoyer ({0})")
a("listing_card_title","İlan","Listing","الإعلان","Annonce")
a("suggested","Önerilen fiyat: {0}","Suggested price: {0}","السعر المقترح: {0}","Prix conseillé : {0}")
a("demand_line","Beklenen ilgi: {0}","Expected interest: {0}","الاهتمام المتوقع: {0}","Intérêt attendu : {0}")
a("demand_high","Yüksek","High","مرتفع","Élevé")
a("demand_mid","Orta","Medium","متوسط","Moyen")
a("demand_low","Düşük","Low","منخفض","Faible")
a("btn_list","İlana Koy","List for Sale","اعرض للبيع","Mettre en vente")
a("btn_update_price","Fiyatı Güncelle","Update Price","حدّث السعر","Mettre à jour le prix")
a("btn_unlist","İlandan Kaldır","Remove Listing","أزل الإعلان","Retirer l'annonce")
a("toast_listed","İlan yayında.","Listing is live.","الإعلان منشور.","Annonce en ligne.")
a("dealer_hint","Acelen varsa aracı hemen bir toptancıya değer kaybıyla satabilirsin.","In a hurry? Sell to a dealer right away at a discount.","مستعجل؟ بع لتاجر جملة فوراً بسعر مخفض.","Pressé ? Vends tout de suite à un grossiste avec décote.")
a("btn_dealer","Toptancıya Sat ({0})","Sell to Dealer ({0})","بع لتاجر الجملة ({0})","Vendre au grossiste ({0})")
a("btn_dealer_short","Toptancıya Sat","Sell to Dealer","بع لتاجر الجملة","Vendre au grossiste")
a("dealer_confirm","Araç {0} karşılığında hemen satılacak. Emin misin?","The car will be sold now for {0}. Are you sure?","ستباع السيارة الآن بـ {0}. هل أنت متأكد؟","La voiture sera vendue pour {0}. Tu es sûr ?")
a("toast_dealer_sold","Toptancıya satıldı: {0}","Sold to dealer: {0}","بيعت لتاجر الجملة: {0}","Vendue au grossiste : {0}")

# eğitim
a("training_title","Eğitim ve Gelişim","Training & Growth","التدريب والتطوير","Formation et progrès")
a("learning_skill","Öğrenme Becerisi","Learning Skill","مهارة التعلم","Compétence d'apprentissage")
a("learning_desc","Eğitimleri %{0} hızlandırır ve daha kaliteli müşteri gelme ihtimalini artırır.","Speeds up trainings by {0}% and raises the chance of better customers.","تسرّع التدريبات بنسبة {0}٪ وتزيد فرصة قدوم زبائن أفضل.","Accélère les formations de {0} % et attire de meilleurs clients.")
a("active_training","DEVAM EDEN EĞİTİM","TRAINING IN PROGRESS","تدريب جارٍ","FORMATION EN COURS")
a("days_left","Kalan süre: {0} gün","Time left: {0} days","المتبقي: {0} أيام","Temps restant : {0} jours")
a("days_n","{0} gün","{0} days","{0} أيام","{0} jours")
a("cost","Bedel","Cost","التكلفة","Coût")
a("duration","Süre","Duration","المدة","Durée")
a("requirement","Açılma şartı","Requirement","الشرط","Condition")
a("req_level","Seviye {0}","Level {0}","المستوى {0}","Niveau {0}")
a("btn_train","Eğitimi Başlat (Kademe {0})","Start Training (Tier {0})","ابدأ التدريب (المرحلة {0})","Lancer la formation (palier {0})")
a("training_maxed","Bu eğitimi tamamladın.","Training completed.","أكملت هذا التدريب.","Formation terminée.")
a("toast_training_started","Eğitim başladı.","Training started.","بدأ التدريب.","Formation commencée.")
a("toast_training_done","{0} eğitimi tamamlandı!","{0} training completed!","اكتمل تدريب {0}!","Formation {0} terminée !")
a("train_err_busy","Zaten devam eden bir eğitim var.","A training is already in progress.","هناك تدريب جارٍ بالفعل.","Une formation est déjà en cours.")
a("train_err_max","Bu eğitim tamamlandı.","Already maxed.","اكتمل هذا التدريب.","Déjà au maximum.")
a("train_err_level","Seviyen yetersiz.","Your level is too low.","مستواك غير كافٍ.","Niveau insuffisant.")
a("train_err_no_money","Yetersiz bakiye.","Not enough money.","الرصيد غير كافٍ.","Solde insuffisant.")
a("tr_inspect","Oto Ekspertiz","Car Inspection","فحص السيارات","Expertise auto")
a("tr_inspect_desc","Ekspertiz ücretini düşürür ve tamir masrafı tahminini netleştirir.","Cuts inspection fees and sharpens repair estimates.","يخفض رسوم الفحص ويحسّن تقدير الإصلاح.","Réduit les frais d'expertise et affine les devis de réparation.")
a("tr_haggle","Pazarlık","Haggling","المفاوضة","Négociation")
a("tr_haggle_desc","Satıcıların kabul eşiğini düşürür; daha ucuza alırsın.","Lowers sellers' acceptance threshold; you buy cheaper.","يخفض حد قبول البائعين فتشتري بسعر أقل.","Abaisse le seuil des vendeurs : tu achètes moins cher.")
a("tr_sales","Satış Tekniği","Sales Technique","أسلوب البيع","Technique de vente")
a("tr_sales_desc","Müşteriler daha yüksek öder ve daha sabırlı olur.","Customers pay more and are more patient.","يدفع الزبائن أكثر ويصبحون أكثر صبراً.","Les clients paient plus et sont plus patients.")
a("tr_market","Piyasa Bilgisi","Market Knowledge","معرفة السوق","Connaissance du marché")
a("tr_market_desc","Tahmini değer aralığı daralır; fiyatları daha doğru okursun.","Narrows the estimated value range for accurate pricing.","يضيّق نطاق القيمة التقديرية لتقييم أدق.","Réduit la fourchette de valeur estimée.")
a("tr_learn","Öğrenme","Learning","التعلم","Apprentissage")
a("tr_learn_desc","Tüm eğitimleri kısaltır ve nitelikli müşteri şansını artırır.","Shortens all trainings and improves customer quality.","يقصّر كل التدريبات ويحسّن جودة الزبائن.","Raccourcit toutes les formations et améliore la clientèle.")

# kredi
a("loans_title","Kredi","Loans","القروض","Crédits")
a("loan_cap","Toplam kredi üst sınırı","Total loan cap","الحد الأقصى للقروض","Plafond total")
a("loan_room","Kullanılabilir limit","Available limit","الحد المتاح","Limite disponible")
a("late_rule","Taksit her 7 günde bir otomatik ödenir. Bakiye yetmezse %5 gecikme faizi eklenir ve itibarın düşer.","Installments are paid automatically every 7 days. If funds are short, a 5% late fee applies and reputation drops.","تُدفع الأقساط تلقائياً كل 7 أيام. عند نقص الرصيد تُضاف غرامة 5٪ وتنخفض سمعتك.","Les échéances sont prélevées tous les 7 jours. Si le solde manque : pénalité de 5 % et réputation en baisse.")
a("loan_item","{0} • {1} hafta","{0} • {1} weeks","{0} • {1} أسابيع","{0} • {1} semaines")
a("weekly","Haftalık taksit","Weekly installment","القسط الأسبوعي","Mensualité hebdo")
a("remaining_weeks","Kalan taksit","Installments left","الأقساط المتبقية","Échéances restantes")
a("late_fee","Gecikme bedeli","Late fee","غرامة التأخير","Pénalité de retard")
a("loan_left_total","Kalan toplam","Total remaining","المجموع المتبقي","Total restant")
a("btn_settle","Erken Kapat ({0})","Settle Early ({0})","سدّد مبكراً ({0})","Solder ({0})")
a("toast_loan_done","Kredi tamamen ödendi!","Loan fully repaid!","تم سداد القرض بالكامل!","Crédit entièrement remboursé !")
a("new_loan","Yeni Kredi","New Loan","قرض جديد","Nouveau crédit")
a("loan_cap_reached","Kredi limitine ulaştın.","You reached the loan cap.","وصلت إلى حد القروض.","Plafond de crédit atteint.")
a("term","Vade","Term","المدة","Durée")
a("weeks_n","{0} hf","{0} wk","{0} أسبوع","{0} sem.")
a("interest","Toplam faiz","Total interest","إجمالي الفائدة","Intérêts totaux")
a("total_repay","Toplam geri ödeme","Total repayment","إجمالي السداد","Remboursement total")
a("first_payment","İlk ödeme tarihi","First payment","تاريخ أول دفعة","Premier paiement")
a("last_payment","Son ödeme tarihi","Last payment","تاريخ آخر دفعة","Dernier paiement")
a("btn_take","{0} Kredi Çek","Borrow {0}","اقترض {0}","Emprunter {0}")
a("toast_loan_taken","{0} kredi hesabına geçti.","{0} loan credited.","تم إيداع قرض بقيمة {0}.","Crédit de {0} versé.")
a("err_loan_cap","Kredi limiti aşılıyor.","Loan cap exceeded.","تجاوز حد القروض.","Plafond dépassé.")
a("toast_installment_paid","Kredi taksiti ödendi: {0}","Installment paid: {0}","تم دفع القسط: {0}","Échéance payée : {0}")
a("toast_installment_late","Taksit ödenemedi! Gecikme bedeli eklendi.","Installment missed! Late fee added.","تعذر دفع القسط! أضيفت غرامة تأخير.","Échéance impayée ! Pénalité ajoutée.")
a("toast_new_day","Yeni gün: {0}","New day: {0}","يوم جديد: {0}","Nouveau jour : {0}")

# ayarlar / profil
a("settings_title","Ayarlar","Settings","الإعدادات","Paramètres")
a("language","Dil","Language","اللغة","Langue")
a("sound","Ses ve Titreşim","Sound & Vibration","الصوت والاهتزاز","Son et vibration")
a("music","Müzik","Music","الموسيقى","Musique")
a("sfx","Ses efektleri","Sound effects","المؤثرات الصوتية","Effets sonores")
a("vibration","Titreşim","Vibration","الاهتزاز","Vibration")
a("location","Konum","Location","الموقع","Lieu")
a("location_hint","İstanbul'da müşteri akışı daha yüksektir; hava ve haber her gün değişir.","Istanbul has more customer traffic; weather and news change daily.","في إسطنبول حركة زبائن أعلى؛ الطقس والأخبار تتغير يومياً.","Istanbul attire plus de clients ; météo et actualités changent chaque jour.")
a("btn_reset","Kaydı Sil ve Başa Dön","Delete Save & Restart","احذف الحفظ وابدأ من جديد","Supprimer la sauvegarde")
a("reset_confirm","Tüm ilerlemen silinecek. Bu işlem geri alınamaz.","All progress will be deleted. This cannot be undone.","سيتم حذف كل تقدمك. لا يمكن التراجع.","Toute ta progression sera supprimée. Irréversible.")
a("profile_title","Profil","Profile","الملف الشخصي","Profil")
a("stats","İstatistikler","Statistics","الإحصائيات","Statistiques")
a("stat_level","Seviye","Level","المستوى","Niveau")
a("stat_xp","Toplam XP","Total XP","إجمالي الخبرة","XP totale")
a("stat_day","Oyun günü","Game day","يوم اللعبة","Jour de jeu")
a("stat_sold","Satılan araç","Cars sold","السيارات المباعة","Voitures vendues")
a("stat_bought","Alınan araç","Cars bought","السيارات المشتراة","Voitures achetées")
a("stat_profit","Toplam kâr","Total profit","إجمالي الربح","Profit total")
a("stat_best","En iyi satış kârı","Best sale profit","أفضل ربح","Meilleur bénéfice")
a("stat_rep","İtibar","Reputation","السمعة","Réputation")
a("stat_crates","Açılan kasa","Crates opened","الصناديق المفتوحة","Caisses ouvertes")
a("roadmap_title","Yol Haritası","Roadmap","خريطة الطريق","Feuille de route")
a("roadmap_body","Gelecek sürümlerde: ev satın alma ve geliştirme, evcil hayvan sahiplenme ve eş/partner sistemi. Bu özellikler V1'de yoktur.","Coming in future versions: buying and upgrading a home, adopting pets and a partner system. These are not in V1.","في الإصدارات القادمة: شراء المنزل وتطويره، تبني حيوان أليف ونظام الشريك. هذه الميزات غير متوفرة في V1.","Dans les prochaines versions : achat et amélioration d'une maison, animaux de compagnie et partenaire. Absents de la V1.")

# ödül
a("rewards_title","Seviye Ödülleri","Level Rewards","مكافآت المستوى","Récompenses de niveau")
a("rewards_none","Bekleyen ödül yok.","No pending rewards.","لا مكافآت معلقة.","Aucune récompense en attente.")
a("rewards_next","Seviye {0} için araç sat ve XP kazan.","Sell cars and earn XP to reach level {0}.","بع السيارات واكسب الخبرة للوصول إلى المستوى {0}.","Vends des voitures pour atteindre le niveau {0}.")
a("rewards_history","Alınan ödüller","Claimed rewards","المكافآت المستلمة","Récompenses reçues")
a("reward_cash","Para ödülü","Cash reward","مكافأة نقدية","Récompense en argent")
a("reward_crate","Ödül kasası","Reward crate","صندوق المكافآت","Caisse de récompense")
a("reward_for_level","Seviye {0} ödülü","Level {0} reward","مكافأة المستوى {0}","Récompense niveau {0}")
a("reward_choose","İkisinden birini seç. Seçim kaydedilir ve değiştirilemez.","Choose one. Your choice is saved and final.","اختر واحداً. الاختيار نهائي ويُحفظ.","Choisis-en une. Le choix est définitif.")
a("btn_reward_cash","Para Ödülü: {0}","Cash Reward: {0}","مكافأة نقدية: {0}","Argent : {0}")
a("btn_reward_crate","Ödül Kasasını Aç","Open Reward Crate","افتح صندوق المكافآت","Ouvrir la caisse")
a("toast_cash_reward","{0} hesabına eklendi.","{0} added to your balance.","أضيف {0} إلى رصيدك.","{0} ajoutés à ton solde.")
a("crate_odds_title","Kasa olasılıkları","Crate odds","احتمالات الصندوق","Probabilités de la caisse")
a("crate_money","Oyun içi para","In-game money","مال داخل اللعبة","Argent en jeu")
a("crate_car","Bir araç (seviyene uygun)","A car (matching your level)","سيارة (حسب مستواك)","Une voiture (selon ton niveau)")
a("crate_xp","Bonus XP","Bonus XP","خبرة إضافية","XP bonus")
a("crate_note","Kasalar yalnızca oyun içi ilerlemeyle kazanılır; gerçek parayla satılmaz.","Crates are earned only through gameplay; never sold for real money.","تُكسب الصناديق باللعب فقط ولا تُباع بمال حقيقي.","Les caisses se gagnent en jouant ; jamais vendues contre de l'argent réel.")
a("crate_opening","Kasa açılıyor…","Opening crate…","جارٍ فتح الصندوق…","Ouverture…")
a("crate_result","Kasadan çıkan:","You got:","حصلت على:","Tu as obtenu :")
a("crate_car_garage","Araç galeriye eklendi.","The car was added to your gallery.","أضيفت السيارة إلى معرضك.","Voiture ajoutée à ta galerie.")
a("crate_car_storage","Galeri dolu: araç depoya alındı. İşletmem'den galeriye alabilir veya pazara aktarabilirsin.","Gallery full: car moved to storage. Move it to the gallery or sell it from My Business.","المعرض ممتلئ: نُقلت السيارة إلى المخزن. انقلها أو بعها من «عملي».","Galerie pleine : voiture au dépôt. Déplace-la ou vends-la depuis Mon commerce.")
a("crate_car_cash","Galeri ve depo dolu: araç otomatik satıldı ({0}).","Gallery and storage full: car auto-sold ({0}).","المعرض والمخزن ممتلئان: بيعت السيارة تلقائياً ({0}).","Galerie et dépôt pleins : voiture vendue ({0}).")
a("unlocks","Açılanlar","Unlocks","يفتح","Débloque")
a("unlock_2","Orta sınıf araçlar, Aile müşterileri, galeri geliştirmesi","Mid-range cars, Family customers, gallery upgrade","سيارات متوسطة، زبائن العائلات، ترقية المعرض","Voitures milieu de gamme, clients Famille, agrandissement")
a("unlock_4","Spor araçlar, Kurumsal müşteriler","Sport cars, Corporate customers","سيارات رياضية، زبائن الشركات","Voitures sportives, clients Entreprise")
a("unlock_7","VIP müşteriler, büyük galeri","VIP customers, bigger gallery","زبائن VIP، معرض أكبر","Clients VIP, galerie plus grande")
a("unlock_10","Premium araçlar, en büyük galeri","Premium cars, largest gallery","سيارات فاخرة، أكبر معرض","Voitures premium, plus grande galerie")

# ================= v1.1 güncellemeleri (aynı anahtar varsa sonraki geçerlidir) =================
a("new_game_city","Şehrini seç","Choose your city","اختر مدينتك","Choisis ta ville")
a("btn_pick_city","Şehrini Seç: {0}","Choose City: {0}","اختر المدينة: {0}","Choisir la ville : {0}")
a("city_pick_title","Şehir Seç","Select City","اختر المدينة","Choisir la ville")
a("city_search","Şehir ara…","Search city…","ابحث عن مدينة…","Rechercher une ville…")
a("location","Şehir","City","المدينة","Ville")
a("location_hint","Büyük şehirlerde müşteri akışı daha yüksektir. İklim hava durumunu etkiler.","Big cities bring more customers. Climate affects the weather.","المدن الكبيرة تجلب زبائن أكثر. المناخ يؤثر على الطقس.","Les grandes villes attirent plus de clients. Le climat influence la météo.")
a("loading_cars","Araçlar hazırlanıyor…","Preparing cars…","جارٍ تجهيز السيارات…","Préparation des voitures…")
a("loading_sound","Ses motoru yükleniyor…","Loading audio…","جارٍ تحميل الصوت…","Chargement du son…")
a("loading_market","Pazar kuruluyor…","Setting up the market…","جارٍ تجهيز السوق…","Mise en place du marché…")
a("save_load","Kayıt","Save","الحفظ","Sauvegarde")
a("btn_main_menu","Ana Menüye Dön","Back to Main Menu","العودة للقائمة الرئيسية","Retour au menu principal")
a("home_debt_line","Borç {0} • Günlük taksit {1}","Debt {0} • Daily installment {1}","الدين {0} • القسط اليومي {1}","Dette {0} • Mensualité quotidienne {1}")
a("tile_business_sub","{0}/{1} araç","{0}/{1} cars","{0}/{1} سيارة","{0}/{1} voitures")
a("tile_market_sub","{0} ilan","{0} listings","{0} إعلان","{0} annonces")
a("tile_training_idle","Becerini geliştir","Level up your skills","طوّر مهاراتك","Améliore tes compétences")
a("tile_training_active","Devam ediyor • {0} dk","In progress • {0} min","جارٍ • {0} د","En cours • {0} min")
a("tile_loans_sub","Borç {0}","Debt {0}","الدين {0}","Dette {0}")
a("tile_loans_none","Borç yok","No debt","لا دين","Aucune dette")
# bekleme / gider
a("wait_cost_hint","Zaman ilerletmek galeri giderine mal olur: saatlik {0}.","Waiting costs gallery expenses: {0} per hour.","تمرير الوقت يكلّف مصاريف المعرض: {0} للساعة.","Attendre coûte des frais de galerie : {0} par heure.")
a("err_wait_money","Galeri gideri için yeterli bakiye yok ({0}).","Not enough money for gallery expenses ({0}).","لا يكفي الرصيد لمصاريف المعرض ({0}).","Solde insuffisant pour les frais de galerie ({0}).")
a("kpi_cars","Araç","Cars","السيارات","Voitures")
a("kpi_listed","İlanda","Listed","معروضة","En vente")
a("kpi_customers","Müşteri","Customers","الزبائن","Clients")
a("visit_offer","Teklif {0}","Offer {0}","العرض {0}","Offre {0}")
a("visit_list","İlan {0}","Ad {0}","الإعلان {0}","Annonce {0}")
a("mood_buyer","Müşteri sabrı","Customer patience","صبر الزبون","Patience du client")
a("mood_seller","Satıcı sabrı","Seller patience","صبر البائع","Patience du vendeur")
a("banner_title","Yeni müşteri geldi!","New customer!","وصل زبون جديد!","Nouveau client !")
a("banner_body","{0} ({1}) • {2} için {3} teklif ediyor.","{0} ({1}) • offers {3} for {2}.","{0} ({1}) • يعرض {3} مقابل {2}.","{0} ({1}) • propose {3} pour {2}.")
a("btn_later","Sonra","Later","لاحقاً","Plus tard")
a("btn_banner_go","Görüş","Talk","تحدث","Parler")
# konuşma çeşitliliği
V=[
("cust_greet",[("Merhaba, aracınıza bakmaya geldim. {0} veririm.","Hello, I came to see your car. I'd pay {0}.","مرحباً، جئت لأرى سيارتك. سأدفع {0}.","Bonjour, je viens voir votre voiture. Je propose {0}."),
 ("İyi günler! İlandaki araç hâlâ satılık mı? {0} düşünüyorum.","Good day! Is the car still for sale? I was thinking {0}.","يوم سعيد! هل السيارة ما زالت للبيع؟ أفكر في {0}.","Bonjour ! La voiture est toujours à vendre ? Je pensais à {0}."),
 ("Selam, aracı beğendim. Nakit {0} versem olur mu?","Hi, I like the car. Would {0} cash work?","مرحباً، أعجبتني السيارة. هل يناسبك {0} نقداً؟","Salut, la voiture me plaît. {0} comptant, ça va ?"),
 ("Merhaba, ilanı gördüm. Fiyatta anlaşabilirsek {0} öderim.","Hello, I saw your ad. If we agree, I'll pay {0}.","مرحباً، رأيت إعلانك. إذا اتفقنا سأدفع {0}.","Bonjour, j'ai vu l'annonce. Si on s'entend, je paie {0}.")]),
("counter_bubble",[("Bu araç için {0} istiyorum.","I want {0} for this car.","أريد {0} لهذه السيارة.","Je veux {0} pour cette voiture."),
 ("Benim fiyatım {0}.","My price is {0}.","سعري هو {0}.","Mon prix est {0}."),
 ("{0} olursa hemen anlaşırız.","At {0} we have a deal right away.","عند {0} نتفق فوراً.","À {0}, on conclut tout de suite.")]),
("cust_accept",[("Tamam, anlaştık!","Okay, we have a deal!","حسناً، اتفقنا!","D'accord, marché conclu !"),
 ("Güzel, kabul ediyorum. Hayırlı olsun!","Great, I accept. Congratulations!","ممتاز، أقبل. مبروك!","Parfait, j'accepte. Félicitations !"),
 ("Pekâlâ, bu fiyata alıyorum.","Alright, I'll take it at that price.","حسناً، سآخذها بهذا السعر.","Très bien, je la prends à ce prix.")]),
("cust_counter",[("Biraz indirin… {0} olur.","Come down a bit… {0} works.","أنزل قليلاً… {0} مناسب.","Baissez un peu… {0} ça va."),
 ("Hımm, {0} dersek anlaşabiliriz.","Hmm, if we say {0} we can agree.","همم، إذا قلنا {0} نتفق.","Hmm, à {0} on peut s'entendre."),
 ("Son sözüm {0}, daha fazlasına gücüm yetmez.","My last word is {0}, I can't stretch further.","كلمتي الأخيرة {0}، لا أستطيع أكثر.","Mon dernier mot : {0}, je ne peux pas plus.")]),
("cust_low",[("Bu fiyat bütçemin çok üstünde.","That is far above my budget.","هذا السعر أعلى بكثير من ميزانيتي.","C'est bien au-dessus de mon budget."),
 ("Bu kadar veremem, biraz makul olalım.","I can't pay that much, let's be reasonable.","لا أستطيع دفع هذا، لنكن معقولين.","Je ne peux pas payer autant, soyons raisonnables."),
 ("Fiyat çok yüksek, başka galerilere de bakıyorum.","Too expensive, I'm checking other galleries too.","السعر مرتفع جداً، أنظر في معارض أخرى أيضاً.","Trop cher, je regarde d'autres galeries.")]),
("cust_leave",[("Anlaşamadık, başka galeriye bakacağım.","We can't agree, I'll check another gallery.","لم نتفق، سأذهب إلى معرض آخر.","On ne s'entend pas, je vais voir ailleurs."),
 ("Sabrım taştı, kolay gelsin.","I'm out of patience. Take care.","نفد صبري، بالتوفيق.","Ma patience a des limites. Bonne continuation."),
 ("Bu fiyatla olmaz. İyi günler!","Not at this price. Good day!","بهذا السعر لا. يوم سعيد!","Pas à ce prix. Bonne journée !")]),
("offer_bubble",[("{0} verebilirim.","I can pay {0}.","يمكنني دفع {0}.","Je peux payer {0}."),
 ("Elimdeki bütçe {0}.","My budget is {0}.","ميزانيتي {0}.","Mon budget est de {0}."),
 ("{0} olursa hemen alırım.","At {0} I'll take it right away.","عند {0} سآخذها فوراً.","À {0}, je la prends tout de suite.")]),
("sell_greet",[("Alo, ilan için mi arıyorsunuz? Fiyat {0}.","Hello, calling about the ad? The price is {0}.","ألو، تتصل بخصوص الإعلان؟ السعر {0}.","Allô, c'est pour l'annonce ? Le prix est de {0}."),
 ("Merhaba, araç duruyor. İstediğim {0}.","Hi, the car is available. I'm asking {0}.","مرحباً، السيارة متوفرة. أطلب {0}.","Salut, la voiture est dispo. Je demande {0}."),
 ("Buyurun, ilanı görmüşsünüz. Fiyatı {0}.","Go ahead, you saw the ad. The price is {0}.","تفضل، رأيت الإعلان. السعر {0}.","Je vous écoute, vous avez vu l'annonce. Prix : {0}.")]),
("sell_accept",[("Tamam, anlaştık. {0} olsun.","Alright, deal. {0} it is.","حسناً، اتفقنا. {0}.","D'accord, marché conclu. {0}."),
 ("Peki, {0}'ye veriyorum. Hayırlı olsun.","Fine, it's yours for {0}. Congratulations.","حسناً، لك بـ {0}. مبروك.","Bon, elle est à vous pour {0}. Félicitations."),
 ("Olur, {0} üzerinden kapatalım.","Okay, let's close at {0}.","حسناً، نغلق عند {0}.","Ok, concluons à {0}.")]),
("sell_counter",[("Hımm… {0} olursa düşünürüm.","Hmm… I could do {0}.","همم… قد أقبل بـ {0}.","Hmm… je peux faire {0}."),
 ("Biraz daha çıkın, {0} diyelim.","Go a bit higher, let's say {0}.","ارفع قليلاً، لنقل {0}.","Montez un peu, disons {0}."),
 ("Pazarlık payı var ama {0}'nin altına inemem.","There's some room, but not below {0}.","هناك مجال للتفاوض لكن ليس أقل من {0}.","Il y a une marge, mais pas sous {0}.")]),
("sell_sad",[("Bu teklif biraz kırıcı… {0}'den aşağı inemem.","That's a bit insulting… I can't go below {0}.","هذا العرض مهين قليلاً… لا أستطيع النزول عن {0}.","C'est vexant… je ne descends pas sous {0}."),
 ("Aracıma değer biçmişsiniz galiba… {0} derim.","You undervalue my car… I'd say {0}.","يبدو أنك تقلل من قيمة سيارتي… أقول {0}.","Vous sous-estimez ma voiture… je dirais {0}."),
 ("Üzdünüz beni, en az {0} lazım.","You upset me, I need at least {0}.","أحزنتني، أحتاج {0} على الأقل.","Vous me peinez, il me faut au moins {0}.")]),
("sell_angry",[("Ciddi misiniz?! Bu fiyata aracımı verecek değilim!","Are you serious?! I'm not giving the car away!","هل أنت جاد؟! لن أعطي سيارتي بهذا السعر!","Sérieusement ?! Je ne brade pas ma voiture !"),
 ("Şaka mı yapıyorsunuz? Bu fiyat hakaret!","Is this a joke? That price is an insult!","هل تمزح؟ هذا السعر إهانة!","C'est une blague ? Ce prix est une insulte !"),
 ("Bu teklifle vakit kaybediyoruz!","We're wasting time with this offer!","نضيع الوقت بهذا العرض!","On perd notre temps avec cette offre !")]),
("sell_end",[("Yeter, görüşmeyi bitiriyorum. İyi günler.","That's enough, I'm ending this call. Goodbye.","كفى، سأنهي المكالمة. مع السلامة.","Ça suffit, je raccroche. Au revoir."),
 ("Sabrım kalmadı, başka alıcıya satarım. Hoşça kalın.","I'm out of patience, I'll sell to someone else. Bye.","نفد صبري، سأبيع لشخص آخر. وداعاً.","Je n'ai plus de patience, je vends à un autre. Adieu.")]),
]
for key,items in V:
    for i,(tr,en,ar,fr) in enumerate(items,1):
        a("%s_%d"%(key,i),tr,en,ar,fr)
# kredi
a("late_rule","Taksitler her gün otomatik çekilir. Bakiye yetmezse %5 gecikme bedeli eklenir ve itibarın düşer.","Installments are withdrawn automatically every day. If funds are short, a 5% late fee applies and reputation drops.","تُسحب الأقساط تلقائياً كل يوم. عند نقص الرصيد تُضاف غرامة 5٪ وتنخفض سمعتك.","Les échéances sont prélevées chaque jour. Si le solde manque : pénalité de 5 % et réputation en baisse.")
a("loan_item","{0} • {1} ay","{0} • {1} months","{0} • {1} أشهر","{0} • {1} mois")
a("months_n","{0} ay","{0} mo","{0} شهر","{0} mois")
a("daily","Günlük taksit","Daily installment","القسط اليومي","Mensualité quotidienne")
a("remaining_days","Kalan gün","Days left","الأيام المتبقية","Jours restants")
a("paid_pct","Ödenen","Paid","المدفوع","Payé")
a("loan_level_cap","Seviye limiti","Level limit","حد المستوى","Limite de niveau")
a("loan_train_cap","Eğitim limiti","Training limit","حد التدريب","Limite de formation")
a("loan_limit","Geçerli limit","Current limit","الحد الحالي","Limite actuelle")
a("loan_tip","Yeni kredi için mevcut kredinin en az %40'ı ödenmiş olmalı. Limit; seviye atlayarak veya Kredi Kullanımı eğitimiyle artar.","A new loan needs at least 40% of your current loan repaid. The limit grows with level or the Credit Use training.","للحصول على قرض جديد يجب سداد 40٪ على الأقل من القرض الحالي. يزداد الحد بالمستوى أو بتدريب استخدام الائتمان.","Un nouveau crédit exige 40 % du crédit actuel remboursé. La limite augmente avec le niveau ou la formation Crédit.")
a("err_loan_40","Mevcut krediyi en az %40 ödemeden yeni kredi alamazsın (şu an %{0}).","You can't take a new loan before repaying 40% of the current one (now {0}%).","لا يمكنك أخذ قرض جديد قبل سداد 40٪ من القرض الحالي (حالياً {0}٪).","Pas de nouveau crédit avant d'avoir remboursé 40 % de l'actuel (actuellement {0} %).")
a("settle_hint","Erken kapatmada kalan faizin yalnızca %25'i alınır.","Early settlement charges only 25% of the remaining interest.","عند السداد المبكر تُحتسب 25٪ فقط من الفائدة المتبقية.","Le solde anticipé ne facture que 25 % des intérêts restants.")
# eğitim
a("training_hint","Eğitimler sırayla, tek seferde bir tane yapılır. Süre oyun içi dakikadır; zaman, işlemlerle ve beklemeyle ilerler.","Trainings run one at a time. Duration is in-game minutes; time advances with actions and waiting.","التدريبات تتم واحداً تلو الآخر. المدة بدقائق اللعبة؛ يمر الوقت بالإجراءات والانتظار.","Les formations se font une par une. La durée est en minutes de jeu ; le temps avance avec les actions et l'attente.")
a("time_left_min","Kalan: {0} dk","Left: {0} min","المتبقي: {0} د","Reste : {0} min")
a("tier_n","Kademe {0}","Tier {0}","المرحلة {0}","Palier {0}")
a("btn_advance_time","Zamanı İlerlet (+15 dk • {0})","Advance Time (+15 min • {0})","مرّر الوقت (+15 د • {0})","Avancer (+15 min • {0})")
a("effect","Etki","Effect","التأثير","Effet")
a("min_n","{0} dk","{0} min","{0} د","{0} min")
a("btn_train_full","Başlat (Kademe {0}) • {1} • {2}","Start (Tier {0}) • {1} • {2}","ابدأ (المرحلة {0}) • {1} • {2}","Lancer (palier {0}) • {1} • {2}")
a("train_locked_busy","Başka bir eğitim sürüyor","Another training is running","هناك تدريب آخر جارٍ","Une autre formation est en cours")
a("tr_credit","Kredi Kullanımı","Credit Use","استخدام الائتمان","Usage du crédit")
a("tr_credit_desc","Kredi limitini artırır. 3. kademede tüm limit (₺2.000.000) açılır.","Raises your loan limit. Tier 3 unlocks the full limit (₺2,000,000).","يرفع حد القروض. المرحلة 3 تفتح الحد الكامل (₺2,000,000).","Augmente ta limite de crédit. Le palier 3 débloque tout (₺2 000 000).")
a("tr_inspect_desc","Ekspertiz ücretini düşürür ve tamir masrafı tahminini netleştirir.","Cuts inspection fees and sharpens repair estimates.","يخفض رسوم الفحص ويحسّن تقدير الإصلاح.","Réduit les frais d'expertise et affine les devis.")
# kilitler
a("unlock_2","Orta sınıf araçlar, Aile müşterileri, galeri geliştirmesi","Mid-range cars, Family customers, gallery upgrade","سيارات متوسطة، زبائن العائلات، ترقية المعرض","Voitures milieu de gamme, clients Famille, agrandissement")
a("unlock_4","Daha pahalı araçlar, Kurumsal müşteriler","Pricier cars, Corporate customers","سيارات أغلى، زبائن الشركات","Voitures plus chères, clients Entreprise")
a("unlock_6","Kredi limiti ₺750.000, elektrikli araçlar","Loan limit ₺750,000, electric cars","حد القروض ₺750,000، سيارات كهربائية","Limite de crédit ₺750 000, voitures électriques")
a("unlock_7","VIP müşteriler, premium araçlar","VIP customers, premium cars","زبائن VIP، سيارات فاخرة متوسطة","Clients VIP, voitures premium")
a("unlock_10","Spor ve premium segment, büyük galeri","Sport & premium segment, bigger gallery","فئة الرياضية والفاخرة، معرض أكبر","Segment sport et premium, galerie plus grande")
a("unlock_11","Kredi limiti ₺1.000.000","Loan limit ₺1,000,000","حد القروض ₺1,000,000","Limite de crédit ₺1 000 000")
a("unlock_12","Lüks araçlar açılır","Luxury cars unlock","تُفتح السيارات الفاخرة","Les voitures de luxe se débloquent")
a("unlock_16","Üst düzey lüks araçlar, kredi limiti ₺1.500.000","Top luxury cars, loan limit ₺1,500,000","سيارات فاخرة راقية، حد القروض ₺1,500,000","Voitures de luxe haut de gamme, limite ₺1 500 000")
a("unlock_20","Kredi limiti ₺2.000.000, ultra lüks araçlar","Loan limit ₺2,000,000, ultra-luxury cars","حد القروض ₺2,000,000، سيارات فائقة الفخامة","Limite ₺2 000 000, voitures ultra-luxe")

a('tile_training_active','Devam ediyor · {0}','In progress · {0}','جارٍ · {0}','En cours · {0}')

a('tr_learn_desc','Müşteri kalitesini artırır. Eğitimler gerçek süreyle ve sırayla tamamlanır.','Improves customer quality. Courses finish sequentially in real time.','يحسن العملاء. التدريبات متتالية بالوقت الحقيقي.','Améliore les clients. Formations successives en temps réel.')

a('loan_tip','Seviye veya Kredi Kullanımı eğitimi kredi limitini artırır. Eğitim 10 kademedir.','Player level or Credit Training increases the limit. Training has 10 tiers.','المستوى أو تدريب الائتمان يزيد الحد. 10 مراحل.','Le niveau ou la formation crédit augmente la limite. 10 paliers.')

a('welcome_body','₺300.000 ile başlıyorsun. İlk aracını pazardan al, hazırla ve ilana koy. Eğitim ve günlük kasa gelişimini destekler.','Start with ₺300,000. Buy, prepare and list your first car. Training and daily crates support progression.','ابدأ بـ ₺300,000. اشتر وجهز واعلن سيارتك. التدريب والصناديق اليومية تساعدك.','Commencez avec ₺300 000. Achetez, préparez et annoncez une voiture. Formations et cadeaux favorisent la progression.')

a('cust_greet_4','İlan açıklamasını okudum. Masrafları düşününce {0} teklif edebilirim.','I read the listing. Considering expenses, I can offer {0}.','قرأت الإعلان. مع احتساب المصاريف أقدم {0}.','J’ai lu l’annonce. Avec les frais, je peux proposer {0}.')

a('cust_greet_5','Aracı günlük kullanacağım. Bütçem belli; {0} sizin için uygun mu?','I need it for daily use. My budget is fixed; would {0} work?','أحتاجها يومياً. ميزانيتي محددة؛ هل يناسبك {0}؟','Pour un usage quotidien. Budget limité ; {0} vous convient ?')

a('cust_counter_4','Anlıyorum, ama ayırabildiğim tutar {0}. Orta noktayı bulalım.','I understand, but I can allocate {0}. Let’s meet halfway.','أتفهم، لكن المتاح {0}. لنجد حلاً وسطاً.','Je comprends, mais je peux consacrer {0}. Trouvons un accord.')

a('cust_counter_5','Ben de ciddi alıcıyım. {0} olursa bugün anlaşabiliriz.','I am serious about buying. At {0}, we can agree today.','أنا جاد. عند {0} نتفق اليوم.','Je suis sérieux. À {0}, on peut conclure aujourd’hui.')

a('cust_low_4','Bu fiyat bütçemin çok üzerinde. Makul bir teklife yaklaşalım.','That is far above my budget. Let’s get closer to a reasonable offer.','هذا يفوق ميزانيتي كثيراً. لنقترب من عرض معقول.','C’est bien au-dessus de mon budget. Revenons à un prix raisonnable.')

a('cust_accept_4','Tamam, fiyat konusunda anlaştık. Satışı tamamlayabiliriz.','Agreed on the price. We can complete the sale.','اتفقنا على السعر. يمكن إتمام البيع.','Prix accepté. Nous pouvons conclure.')

a('cust_leave_4','Bütçemde anlaşamadık. Başka ilanlara bakacağım, kolay gelsin.','We could not agree within my budget. I’ll look at other listings.','لم نتفق ضمن ميزانيتي. سأبحث في إعلانات أخرى.','Pas d’accord dans mon budget. Je vais regarder ailleurs.')

a('goal_wait','İlanlar yayında. İlk alıcı 15–20 saniyede gelecek; İlanlarım sekmesini izle.','Listings are live. First buyer arrives in 15–20 seconds; watch My listings.','الإعلانات نشطة. أول مشترٍ خلال 15–20 ثانية؛ تابع إعلاناتي.','Annonces publiées. Premier acheteur sous 15–20 secondes ; consultez Mes annonces.')

a('tr_sales_desc','Müşteri kalitesini artırır; ödeme bütçesini kademede %0,4 iyileştirir.','Improves buyer quality and increases the payment budget by 0.4% per tier.','يحسن العملاء ويرفع ميزانية الدفع 0.4٪ لكل مرحلة.','Améliore les clients et leur budget de 0,4 % par palier.')

a('unlock_2','Aile müşterileri ve ilan vitrini geliştirmesi','Family customers and listing showcase upgrades','عملاء العائلات وترقية واجهة الإعلانات','Clients Famille et amélioration de la vitrine')

T += [
("customer_rating", "Müşteri memnuniyeti", "Customer satisfaction", "رضا العملاء", "Satisfaction client"),
("review_happy", "Araç ve fiyat beklentimi karşıladı. Tavsiye ederim!", "The car and price met my expectations!", "السيارة والسعر مناسبان!", "Voiture et prix conformes à mes attentes !"),
("review_fair", "Alışveriş iyiydi, araç biraz daha iyi hazırlanabilirdi.", "Good deal, preparation could be better.", "صفقة جيدة، يمكن تحسين التجهيز.", "Bonne affaire, préparation perfectible."),
("review_unhappy", "Araç hazırlığı ve fiyat beni memnun etmedi.", "Condition and price disappointed me.", "الحالة والسعر لم يعجباني.", "État et prix décevants."),
("car_stolen", "Güvenlik yetersizdi: %s çalındı. Güvenliğini geliştir!", "Low security: %s was stolen!", "أمن ضعيف: سُرقت %s!", "Sécurité insuffisante : %s volée !"),
("push_title", "Telefon bildirimleri", "Phone notifications", "إشعارات الهاتف", "Notifications téléphone"),
("push_hint", "İsteğe bağlı: çıkıştan 10 dakika sonra hatırlatma; günde en fazla 3. Kapalı oyunda gelen müşteri, dönüşünde seni bekler.", "Optional: reminder after 10 minutes; max 3/day. Offline inquiries wait for your return.", "اختياري: تذكير بعد 10 دقائق، 3 يومياً كحد أقصى.", "Facultatif : rappel après 10 minutes, 3/jour maximum."),
("push_setup", "Bildirimleri yönet", "Manage notifications", "إدارة الإشعارات", "Gérer les notifications"),
("push_web_only", "Bildirim kurulumu web sürümünde kullanılabilir.", "Notification setup is available on the web version.", "الإعداد متاح في نسخة الويب.", "Configuration disponible sur le Web."),
]

# V1.9.0 navigation and business screens
a("nav_workshop","Galerim","My garage","مرآبي","Mon garage")
a("nav_training","Beceriler","Skills","المهارات","Compétences")
a("menu_training","Beceriler","Skills","المهارات","Compétences")
a("academy_title","Beceriler ve Gelişim","Skills and Growth","المهارات والتطوير","Compétences et progression")
a("my_listings","Satışlar","Sales","المبيعات","Ventes")
a("wallet_title","İŞLETME CÜZDANI","BUSINESS WALLET","محفظة العمل","PORTEFEUILLE")
a("skill_stage","Ustalık {0} / 10","Mastery {0} / 10","الإتقان {0} / 10","Maîtrise {0} / 10")
a("skill_next","Sonraki kazanım","Next benefit","الفائدة التالية","Prochain avantage")
a("skill_locked","Seviye {0} gerekli · İncele","Requires level {0} · Details","يتطلب المستوى {0} · التفاصيل","Niveau {0} requis · Détails")
a("market_filters","Filtreler","Filters","الفلاتر","Filtres")
a("deal_alert_title","İkinci elde fırsat var!","Used car deal!","فرصة سيارة مستعملة!","Offre occasion !")
a("deal_alert_body","Piyasa değerinin altında yeni bir araç geldi.","A new car is priced below market value.","سيارة جديدة بأقل من سعر السوق.","Nouvelle voiture sous le prix du marché.")
a("deal_open","Araca bak →","View car →","عرض السيارة ←","Voir la voiture →")
a("deal_later","Sonra bakarım","Later","لاحقاً","Plus tard")
a("sales_active","{0} aktif ilan","{0} active listings","{0} إعلانات نشطة","{0} annonces actives")
a("sales_waiting","{0} müşteri bekliyor","{0} buyers waiting","{0} عملاء ينتظرون","{0} clients en attente")
a("sales_estimate","İstenen fiyatta tahmini net","Estimated net at asking price","صافي تقديري بالسعر المطلوب","Net estimé au prix demandé")
a("boost_title","Öne çıkar","Promote","ترويج","Promouvoir")
a("boost_body","5 gerçek dakika daha fazla görünürlük. Müşterinin bütçesi değişmez; aşırı fiyat satışı zorlaştırır.","More visibility for 5 real minutes. Buyer budgets stay the same; excessive prices reduce demand.","ظهور أكبر لمدة 5 دقائق حقيقية. ميزانية العميل لا تتغير؛ الأسعار المرتفعة تقلل الطلب.","Visibilité accrue pendant 5 minutes réelles. Le budget des clients reste inchangé ; un prix excessif réduit la demande.")
a("boost_confirm","5 dakika öne çıkar","Promote for 5 minutes","ترويج 5 دقائق","Promouvoir 5 minutes")
a("boost_remaining","Öne çıkarılıyor · {0}","Promoted · {0}","مروّج · {0}","Promotion · {0}")
a("loss_cancel","Satıştan vazgeç · İtibar −1","Cancel sale · Reputation −1","إلغاء البيع · السمعة −1","Annuler la vente · Réputation −1")
a("loss_cancel_hint","Vazgeçersen araç sende kalır, müşteri ayrılır ve itibarın 1 puan düşer.","Canceling keeps the car, dismisses the buyer and costs 1 reputation point.","عند الإلغاء تبقى السيارة لديك ويغادر العميل وتفقد نقطة سمعة.","Annuler conserve la voiture, fait partir le client et coûte 1 point de réputation.")
a("loss_confirm","Zararına satışı onayla","Confirm sale at a loss","تأكيد البيع بخسارة","Confirmer la vente à perte")
a("security_probability","Otomatik koruma ihtimali: %{0}","Automatic protection chance: {0}%","احتمال الحماية التلقائية: {0}%","Protection automatique : {0}%")

a("account_title","Hesabım · Giriş / Kayıt","My account · Sign in / Register","حسابي · الدخول / التسجيل","Mon compte · Connexion / Inscription")
a("account_web","Hesap bağlantısı web sürümünde kullanılabilir.","Accounts are available in the web version.","الحسابات متاحة في إصدار الويب.","Les comptes sont disponibles dans la version web.")
a("course_not_started","Henüz eğitim alınmadı","No training completed yet","لم يكتمل أي تدريب بعد","Aucune formation terminée")
a("course_completed_count","{0} kademe tamamlandı","{0} stages completed","اكتملت {0} مراحل","{0} étapes terminées")
a("course_required_level","Seviye {0} gerekli","Requires level {0}","يتطلب المستوى {0}","Niveau {0} requis")
a("course_next_stage","Tamamlanınca {0}. kademeye geçersin.","Completing this advances you to stage {0}.","عند الإكمال تنتقل إلى المرحلة {0}.","Cette formation vous fait passer à l’étape {0}.")
a("goal_open","Git","Open","افتح","Ouvrir")
a("deal_open","Araca bak","View car","عرض السيارة","Voir la voiture")
a("gallery_customize","Galeriyi kişiselleştir","Customize gallery","تخصيص المعرض","Personnaliser la galerie")
a("gallery_cosmetic","Temel seçenekler ücretsiz. Özel seçenekler oyun parasıyla bir kez alınır; satış ve güvenlik gücünü değiştirmez.","Basic styles are free. Special styles are purchased once with game money; no sales or security advantage.","الأساسي مجاني. الخيارات الخاصة تُشترى مرة بأموال اللعبة دون ميزة بيع أو أمان.","Styles de base gratuits. Achat unique avec l’argent du jeu, sans avantage commercial ou de sécurité.")
a("gallery_name","Tabela adı","Sign name","اسم اللافتة","Nom de l’enseigne")
a("gallery_save_name","Tabela adını kaydet","Save sign name","حفظ اسم اللافتة","Enregistrer le nom")
a("gallery_sign","Tabela","Sign","اللافتة","Enseigne")
a("gallery_floor","Zemin","Floor","الأرضية","Sol")
a("gallery_decor","Dekor","Decor","الديكور","Décor")
a("gallery_classic","Klasik","Classic","كلاسيكي","Classique")
a("gallery_modern","Modern","Modern","حديث","Moderne")
a("gallery_luxury","Lüks","Luxury","فاخر","Luxueux")
a("gallery_selected","Seçili","Selected","محدد","Sélectionné")
a("gallery_use","Kullan","Use","استخدام","Utiliser")
a("push_hint","Telefon bildirimlerini buradan yönetebilirsin.","Manage phone notifications here.","إدارة إشعارات الهاتف هنا.","Gérez les notifications ici.")

a("gallery_packages_hint","Galeri paketleri görünümü yeniler ve kapasiteyi artırır. Satın almadan önce fiyatı ve özellikleri incele.","Gallery packages refresh the building and increase capacity. Check the price and features before buying.","Gallery packages refresh the building and increase capacity. Check the price and features before buying.","Gallery packages refresh the building and increase capacity. Check the price and features before buying.")
a("gallery_name_saved","Tabela adı kaydedildi.","Sign name saved.","Sign name saved.","Sign name saved.")
a("gallery_prestige","Prestij","Prestige","Prestige","Prestige")
a("gallery_package_classic","Cam vitrin, taş döşeme ve giriş bitkileri. Mevcut galerin ücretsiz kalır.","Glass showroom, paved forecourt and planters. Your current gallery stays free.","Glass showroom, paved forecourt and planters. Your current gallery stays free.","Glass showroom, paved forecourt and planters. Your current gallery stays free.")
a("gallery_package_modern","Daha geniş cam cephe, yenilenen tabela, bayraklar ve aydınlatılmış vitrin.","Wider glass facade, new sign, banners and illuminated showroom.","Wider glass facade, new sign, banners and illuminated showroom.","Wider glass facade, new sign, banners and illuminated showroom.")
a("gallery_package_luxury","Geniş vitrin, altın detaylar, bayraklar ve gece giriş aydınlatması.","Spacious showroom, gold details, banners and night entrance lighting.","Spacious showroom, gold details, banners and night entrance lighting.","Spacious showroom, gold details, banners and night entrance lighting.")
a("gallery_package_prestige","En geniş cephe, yükseltilmiş çatı, özel tabela ve gece ışıkları.","Widest facade, raised roof, premium sign and night lighting.","Widest facade, raised roof, premium sign and night lighting.","Widest facade, raised roof, premium sign and night lighting.")
a("gallery_package_price","Paket fiyatı","Package price","Package price","Package price")
a("gallery_package_capacity","En az {0} araç kapasitesi. Daha büyük mevcut kapasiten korunur.","At least {0} car spaces. Your existing larger capacity is retained.","At least {0} car spaces. Your existing larger capacity is retained.","At least {0} car spaces. Your existing larger capacity is retained.")
a("gallery_buy","{0} karşılığında satın al","Buy for {0}","Buy for {0}","Buy for {0}")
a("gallery_buy_confirm","{0} ödeyerek bu galeri paketini alacaksın. Kapasiten en az {1} araç olacak.","Purchase this gallery for {0}. Capacity will be at least {1} cars.","Purchase this gallery for {0}. Capacity will be at least {1} cars.","Purchase this gallery for {0}. Capacity will be at least {1} cars.")
a("gallery_owned_decor","Önceden aldığım dekorlar","Previously purchased decorations","Previously purchased decorations","Previously purchased decorations")
a("gallery_save","Kaydet","Save","حفظ","Enregistrer")
a("gallery_back","Geri dön","Go back","رجوع","Retour")
