const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.dataset={};this.value='';this.textContent='';}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}setAttribute(){}querySelector(){return all(this).find(n=>n.dataset.message)||null;}}
const all=n=>[n,...n.children.flatMap(all)],settle=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));},deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {resolve,promise};};
async function setup(){let session={user:{email:'audit@example.invalid'}},listener,record=null,read=null;const body=new Element('body'),events=[],writes=[],delays=[];
const client={auth:{onAuthStateChange(fn){listener=fn;},getSession:async()=>({data:{session}}),signOut:async()=>{session=null;listener('SIGNED_OUT');},signUp:async()=>({data:{session:null}}),signInWithPassword:async()=>({data:{session:{user:{email:'audit@example.invalid'}}}}),resetPasswordForEmail:async()=>({}),updateUser:async()=>({})},from:()=>({select:()=>({maybeSingle:()=>read?read.promise:Promise.resolve({data:record})})}),rpc:(name,args)=>{writes.push(args);const d=deferred();delays.push(d);return d.promise;}};
const context={createClient:()=>client,location:{origin:'https://audit.invalid'},fetch:async()=>({json:async()=>({url:'mock',publishableKey:'public'})}),document:{body,createElement:t=>new Element(t),addEventListener(){}},window:{},queueMicrotask,setTimeout:()=>1,clearTimeout(){},confirm:()=>false};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/accounts.js','utf8').replace(/^import[^\n]+\n/,''),context);const api=context.window.otoAccount;api.bind(v=>events.push(JSON.parse(v)));api.start();await settle();
const button=text=>{const b=all(body).find(n=>n.tag==='button'&&n.textContent===text);assert(b,'Missing '+text);return b;};
return {api,events,writes,delays,body,button,setRead:d=>read=d,setRecord:r=>record=r,click:async text=>{await button(text).onclick();await settle();}};}
(async()=>{
let s=await setup();await s.click('Devam et');s.api.queue('{"money":1}');const first=s.api.flush();await settle();s.api.queue('{"money":2}');await s.api.open();const logout=s.button('Çıkış yap').onclick();await settle();assert.equal(s.writes.length,1);s.delays[0].resolve({data:1});await settle();assert.equal(s.writes.length,2);assert.equal(s.writes[1].p_snapshot.money,2);assert.equal(s.writes[1].p_revision,1);s.delays[1].resolve({data:2});await logout;await first;assert.equal(s.body.children.length,0);
s=await setup();const read=deferred();s.setRead(read);const continuing=s.button('Devam et').onclick();await settle();await s.click('Misafir olarak devam et');read.resolve({data:{revision:5,snapshot:{money:99}}});await continuing;assert(!s.events.some(e=>e.type==='load'));s.api.queue('{}');await s.api.flush();assert.equal(s.writes.length,0);
s=await setup();await s.click('Devam et');s.api.queue('{"money":3}');const saving=s.api.flush();await settle();await s.api.open();await s.click('Oyuna dön');s.delays[0].resolve({error:{message:'save_conflict'}});await saving;assert(s.events.some(e=>e.type==='notice'&&e.message.includes('başka cihazda')));s.api.queue('{"money":4}');await s.api.flush();assert.equal(s.writes.length,1);
s=await setup();await s.click('Devam et');s.api.queue('{"money":5}');const retry=s.api.flush();await settle();s.delays[0].resolve({error:{message:'network'}});await retry;const recovered=s.api.flush();await settle();s.delays[1].resolve({data:1});await recovered;assert.equal(s.writes[1].p_snapshot.money,5);
console.log('PASS: logout drains active and queued saves, cancelled startup ignores late cloud data, conflict preserves local progress, failed save retries snapshot');
})().catch(e=>{console.error(e);process.exitCode=1;});
